#开发环境
env: dev
server:
  port: 8081

#jwt秘钥
jwt:
  secret-key: admin #获取的key
  exp-time: PT1H #获取时间 （1小时获取一次）
spring:
  redis: #redis配置
    host: localhost
    port: 6379
    password:
    lettuce:
      pool: #连接池配置
        max-active: 20 #连接池最大连接数
        max-idle: 10 #最大空闲连接数
        min-idle: 5 #最小空闲连接数
        max-wait: PT10s  #最大阻塞时间
    timeout: PT10s #连接超时时间

  datasource: #mysql 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minzu?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis-plus:
  # mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志配置
  global-config:
    db-config:
      table-prefix: ms_



